### ISSUE TITLE
Remove duplicated fitting logic

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/DrugResponseModel.jl#230]
You should just call residHill() from residHillAll(), rather than duplicating the Hill curve solving in residHillAll() and getODEparamsAll().

https://github.com/meyer-lab/DrugResponseModel.jl/blob/81facb9bfe6d94b91eeeee7e59b8b50ed2afd4de/src/allDrugs.jl#L32

**Comment by Farnazmdi** [comment]
But the order of the parameters in the array in `getODEparamsAll()` is different from `getODEparams()`.
If I rearrange the parameters, those parameters that are kept the same across the drugs will be estimated each time, separately. Because for each drug I have to pass them along with the parameters for that specific drug. Am I wrong?

**Comment by aarmey** [comment]
If it's the same across drugs you just need to copy in the same parameter each time you call getODEparams...

**Comment by Farnazmdi** [comment]
#239
